add List-form ApplicationUser
Flexberry/Flexberry.AndroidODataOffline.Sample pull request #12
Opened 2023-05-15 04:41 UTC by BannikovRuslan

2023-05-15 07:19 UTC, AntonIV8 requested changes

2023-05-15 07:19 UTC, AntonIV8 commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/ApplicationUserListFormActivity.kt
> +    @RequiresApi(Build.VERSION_CODES.O)
А вот это зачем ? Вроде в MainActivity такого не создавалось

2023-05-15 07:19 UTC, AntonIV8 commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/applicationuserlistformmodel/ApplicationUserListFormViewModel.kt
> +    data class User(
Тут как-то надо использовать модель 
com.flexberry.androidodataofflinesample.data.model.ApplicationUser

В MainViewModel там сейчас state (если ты по аналогии делал). State это другое. По ним отдельная еще задача будет

2023-05-15 07:19 UTC, AntonIV8 commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/applicationuserlistformmodel/SampleData.kt
> +        User(
тут тоже должны быть

com.flexberry.androidodataofflinesample.data.model.ApplicationUser

2023-05-15 07:19 UTC, AntonIV8 commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/applicationuserlistformmodel/ApplicationUserListFormViewModel.kt
> +    data class MainViewModelState (val isOnline: Boolean)
А это зачем ?

2023-05-16 06:43 UTC, VChurekov commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/applicationuserlistformmodel/SampleData.kt
> +object SampleData {
Добавь сюда @Suppress("kotlin:S1192"). Чтобы code smells не ругался.

2023-05-16 10:59 UTC, AntonIV8 approved these changes

2023-05-17 03:46 UTC, merged