Добавлено главное меню
Flexberry/Flexberry.AndroidODataOffline.Sample pull request #9
Opened 2023-05-05 07:03 UTC by BannikovRuslan

2023-05-05 09:10 UTC, AntonIV8 requested changes

2023-05-05 09:10 UTC, AntonIV8 commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/mainmodel/MainScreen.kt
> +        mainButton(modifier = modifier, fontSize = 36.sp, text = "Список")
У каждой кнопки будет своя функция ведь.
Еее каждую нужно наверное оформить в виде отдельной функции (это и к кнопке offline относится).

fun addButton
fun listButton
fun onlineButton

2023-05-05 09:10 UTC, AntonIV8 commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/mainmodel/MainViewModel.kt
> +    data class MVMState (val isOnline: Boolean)
Аббревиатуры нежелательны. Называть как есть MainViewModelState.

2023-05-05 09:10 UTC, AntonIV8 commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/theme/Theme.kt
> +        secondary = TextBlack,
мне кажется тут должны быть конкретные названия переменных, а не общие primary secondary.
Мб поэтому у меня совсем другие цвета на телефоне

2023-05-10 04:36 UTC, AntonIV8 requested changes

2023-05-10 04:36 UTC, AntonIV8 commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/mainmodel/MainScreen.kt
> +    onClick: () -> Unit,
А вот это для чего ?

2023-05-10 04:36 UTC, AntonIV8 commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/theme/Color.kt
> +var TextBlack = Color.Black
Наверное эта переменную нужно назвать просто Black. Я так понял в material design не совсем правильно привязываться к конкретным элементам (в данном случае text), есть только первичный, вторичный и т.д цвета.

2023-05-10 04:36 UTC, AntonIV8 commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/theme/Theme.kt
> +        dynamicColor: Boolean = false,
Добавить коммент

2023-05-10 10:38 UTC, BannikovRuslan commented on src/AndroidODataOfflineSample/app/src/main/java/com/flexberry/androidodataofflinesample/ui/mainmodel/MainScreen.kt
> +    onClick: () -> Unit,
Параметры функции. Если вопрос про "onClick: () -> Unit" - функция, которая ничего не возвращает. [Тут](https://www.bestprog.net/ru/2021/10/07/kotlin-functions-with-a-single-expression-unit-type-ru/#:~:text=%D0%95%D1%81%D0%BB%D0%B8%20%D0%B2%20%D1%82%D0%B5%D0%BB%D0%B5%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D0%BD%D0%B5,%D0%BA%D0%B0%D0%BA%D0%BE%D0%B3%D0%BE%2D%D1%82%D0%BE%20%D1%82%D0%B8%D0%BF%D0%B0%20%D1%8F%D0%B2%D0%BB%D1%8F%D0%B5%D1%82%D1%81%D1%8F%20%D0%BE%D0%B1%D1%8F%D0%B7%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC) можно посмотреть про Unit.

2023-05-10 11:35 UTC, VChurekov approved these changes

2023-05-14 03:50 UTC, AntonIV8 approved these changes

2023-05-14 03:51 UTC, merged